### ISSUE TITLE
Failure on activation in Wordpress 6.01 & Php 8.0.20

### ISSUE THREAD

**Issue by Trying2Fixit** [webdevconcord/wordpress-concordpaybutton#1]
Install, and upon activation from the wordpress back end, there occurs this error:

Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method ConcordPay_Button::cpb_activate() cannot be called statically in /home/DOMAIN/DOMAIN.org/wp-includes/class-wp-hook.php:307 Stack trace: #0 /home/DOMAIN/DOMAIN.org/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #1 /home/DOMAIN/DOMAIN.org/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #2 /home/DOMAIN/DOMAIN.org/wp-admin/plugins.php(194): do_action('activate_wordpr...') #3 {main} thrown in /home/DOMAIN/DOMAIN.org/wp-includes/class-wp-hook.php on line 307

**Comment by webdevconcord** [comment]
Fixed on v1.1
